version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: aneotop/web1:nc 
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 10M
      restart_policy:
        condition: on-failure
    ports:
      - "80:1500"
    networks:
      - webnet
networks:
  webnet:
